#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       you can try running the script with `bash` or `sh bash`.
#
#   (2) Avoid modifying this script unless you know what you are doing -- it
#       Just uses sensible defaults and runs Gradle fairly intelligently.
#
##############################################################################

# Can use an optional init script when this script is sourced so that you can
# adjust some initial state before the main script runs.
if [ -z "$GRADLE_INIT_DIR" ] ; then
  eval "$(grep '^GRADLE_INIT_DIR=' "$0" | tail -1)"
fi
if [ -z "$GRADLE_INIT_DIR" ] ; then
  GRADLE_INIT_DIR=gradle
fi
sourceScriptFile="${GRADLE_INIT_DIR}/init.gradle"
if [ ! -f "$sourceScriptFile" ] && [ ! -f "${sourceScriptFile}.kts" ] ; then
  sourceScriptFile=""
fi

exec "$0".bat "$@"
