package com.qa.automation.codegen;

import com.qa.automation.models.TestCase;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Generates JUnit test code from test case models
 */
public class JUnitCodeGenerator {
    private static final Logger logger = LoggerFactory.getLogger(JUnitCodeGenerator.class);
    
    private String packageName;
    private String className;

    public JUnitCodeGenerator(String packageName, String className) {
        this.packageName = packageName;
        this.className = className;
    }

    /**
     * Generate JUnit test class code from test cases
     */
    public String generateTestClass(List<TestCase> testCases) {
        logger.info("Generating JUnit test class with {} test cases", testCases.size());

        StringBuilder code = new StringBuilder();

        // Package and imports
        code.append(generatePackageAndImports());
        code.append("\n");

        // Class declaration
        code.append("/**\n");
        code.append(" * Auto-generated JUnit test class\n");
        code.append(" * Generated by AI Test Case Generator\n");
        code.append(" */\n");
        code.append("public class ").append(className).append(" {\n\n");

        // Setup method
        code.append(generateSetupMethod());
        code.append("\n");

        // Teardown method
        code.append(generateTeardownMethod());
        code.append("\n");

        // Test methods
        for (TestCase testCase : testCases) {
            code.append(generateTestMethod(testCase));
            code.append("\n");
        }

        // Close class
        code.append("}\n");

        return code.toString();
    }

    private String generatePackageAndImports() {
        return "package " + packageName + ";\n\n" +
               "import org.junit.Before;\n" +
               "import org.junit.After;\n" +
               "import org.junit.Test;\n" +
               "import static org.junit.Assert.*;\n" +
               "import org.slf4j.Logger;\n" +
               "import org.slf4j.LoggerFactory;\n";
    }

    private String generateSetupMethod() {
        return "    private static final Logger logger = LoggerFactory.getLogger(" + className + ".class);\n\n" +
               "    /**\n" +
               "     * Setup method - runs before each test\n" +
               "     */\n" +
               "    @Before\n" +
               "    public void setUp() {\n" +
               "        logger.info(\"Setting up test fixtures\");\n" +
               "        // TODO: Initialize test fixtures, setup test data, open browser, etc.\n" +
               "    }\n";
    }

    private String generateTeardownMethod() {
        return "    /**\n" +
               "     * Teardown method - runs after each test\n" +
               "     */\n" +
               "    @After\n" +
               "    public void tearDown() {\n" +
               "        logger.info(\"Tearing down test fixtures\");\n" +
               "        // TODO: Clean up test data, close browser, reset state, etc.\n" +
               "    }\n";
    }

    private String generateTestMethod(TestCase testCase) {
        StringBuilder method = new StringBuilder();

        // Method comment with documentation
        method.append("    /**\n");
        method.append("     * Test: ").append(testCase.getDescription()).append("\n");
        method.append("     * Type: ").append(testCase.getTestType()).append("\n");
        method.append("     * Priority: ").append(testCase.getPriority()).append("\n");
        
        if (!testCase.getPreconditions().isEmpty()) {
            method.append("     * Preconditions:\n");
            for (String precondition : testCase.getPreconditions()) {
                method.append("     *   - ").append(precondition).append("\n");
            }
        }
        
        method.append("     */\n");

        // @Test annotation
        method.append("    @Test\n");
        method.append("    public void ").append(testCase.getTestName()).append("() {\n");
        method.append("        logger.info(\"Running test: ").append(testCase.getTestName()).append("\");\n\n");

        // Preconditions
        if (!testCase.getPreconditions().isEmpty()) {
            method.append("        // Preconditions\n");
            for (String precondition : testCase.getPreconditions()) {
                method.append("        // ").append(precondition).append("\n");
            }
            method.append("\n");
        }

        // Test steps
        method.append("        // Test Steps\n");
        int stepNumber = 1;
        for (String step : testCase.getTestSteps()) {
            method.append("        // Step ").append(stepNumber++).append(": ").append(step).append("\n");
        }
        method.append("\n");

        // Expected result assertion
        method.append("        // Expected Result: ").append(testCase.getExpectedResult()).append("\n");
        method.append("        // TODO: Add assertions\n");
        method.append("        assertTrue(\"Test assertion needed\", true);\n");
        method.append("    }\n");

        return method.toString();
    }

    /**
     * Save generated code to a file (handled by caller)
     */
    public String getGeneratedCode(List<TestCase> testCases) {
        return generateTestClass(testCases);
    }
}
